#!/usr/bin/env python3

import sys


def add_check_digit(id_str):
    total = sum(
        i * int(digit)
        for i, digit in enumerate(reversed(id_str), start=2)
    )
    if total % 11 == 10:
        return id_str + 'x'
    else:
        return id_str + str(total % 11)


if __name__ == '__main__':
    try:
        id_str = sys.argv[1]
    except IndexError:
        sys.exit(f"Usage: {__file__} <SIERRA_ID>")

    if len(id_str) == 7:
        print(add_check_digit(id_str))
    elif len(id_str) == 8 and id_str[1:].isnumeric():
        print(id_str[0] + add_check_digit(id_str[1:]))
    else:
        sys.exit(f"Not a Sierra ID: {id_str}")
