#!/usr/bin/env bash

set -o errexit
set -o nounset

mkdir -p ~/Documents/backups/goodreads

cd ~/repos/backup-goodreads
/Users/alexwlchan/.virtualenvs/goodreads/bin/python \
  backup_goodreads.py \
  --output ~/Documents/backups/goodreads/goodreads_reviews_$(date +"%Y-%m-%d").json \
  --user-id=60854850 \
  --api-key=$(cat api_key.txt) \

osascript -e '
  tell application "Things3"
    repeat with todayToDo in to dos of list "Today"
      if ((name of todayToDo) = "Do a Goodreads backup") then
        set status of todayToDo to completed
      end if
    end repeat
  end tell
'
