#!/usr/bin/env python3

import sys

import httpx


def has_item_with_id(work, *, item_id):
    for item in work["items"]:
        if any(id["value"] == item_id for id in item["identifiers"]):
            return True
    return False


if __name__ == "__main__":
    try:
        item_id = sys.argv[1]
    except IndexError:
        sys.exit(f"Usage: {__file__} <ITEM_ID>")

    resp = httpx.get(
        "https://api.wellcomecollection.org/catalogue/v2/works",
        params={"query": item_id, "include": "items,identifiers"},
    )

    resp.raise_for_status()

    from pprint import pprint

    result_list = resp.json()
    try:
        matching_work = next(
            w for w in resp.json()["results"] if has_item_with_id(w, item_id=item_id)
        )
        bib_id = next(
            id
            for id in matching_work["identifiers"]
            if id["identifierType"]["id"] == "sierra-system-number"
        )["value"]
        print(bib_id)
    except StopIteration:
        print("???")
