#!/usr/bin/env osascript

-- Convert an Acorn file to another format (for example, PNG or JPEG)
--
-- Takes two paths as arguments: the original path and the export path.
-- For example:
--
--    convert_acorn ~/Desktop/fire.acorn ~/Desktop/fire.png
--
-- will create a new PNG image.
--
-- The script tries to be well-behaved about your windows: if the Acorn file
-- is already open for editing, it uses that, otherwise it opens the file
-- and then closes it afterward.

on run argv
  if (count of argv) is not 2
    log "Usage: " & (name of me) &" <ORIGINAL_PATH> <EXPORT_PATH>"
    error number 1
  end if

  set arg1 to (item 1 of argv)
  set arg2 to (item 2 of argv)
  set workingDir to (do shell script "pwd") & "/"

  if arg1 starts with "/"
    set originalPath to arg1
  else
    set originalPath to workingDir & arg1
  end if

  if arg2 starts with "/"
    set exportPath to arg2
  else
    set exportPath to workingDir & arg2
  end if

  tell application "Acorn"
    repeat with theWindow in (every window)
      set theDocument to (document of theWindow)
      if theDocument is not missing value then
        set thePath to (file of theDocument)
        if thePath is not missing value then
          if (POSIX path of thePath) = originalPath then
            save theDocument in exportPath
            return
          end if
        end if
      end if
    end repeat

    set theDocument to (open originalPath)
    save theDocument in exportPath
    close theDocument
  end tell
end run
