#!/usr/bin/env python3
# -*- encoding: utf-8

import glob
import pathlib
import subprocess
import sys


def get_paths(patterns):
    for p in patterns:
        for path in glob.iglob(p):
            yield pathlib.Path(path)


try:
    patterns = sys.argv[1:]
except IndexError:
    sys.exit(f"Usage: {__file__} <PATH> ..")


for path in get_paths(patterns):
    assert path.suffix == ".acorn", path

    acorn_path = path
    png_path = acorn_path.with_suffix(".png")

    print(f"Converting {acorn_path} to {png_path}...")

    subprocess.check_call([
        "export_acorn_file", acorn_path.resolve(), png_path.resolve()
    ])
