#!/usr/bin/env python
# -*- encoding: utf-8

import collections
import os


def count_files_under(d):
    return sum(len(filenames) for _, _, filenames in os.walk(d))


counts = collections.Counter({".": 0})

for f in os.listdir("."):
    if os.path.isdir(f):
        counts[f] = count_files_under(f)
    else:
        counts["."] += 1

total = sum(counts.values())

for dirname, count in reversed(counts.most_common()):
    print(" \033[33m%s\033[0m %s" % (
        str(count).rjust(len(str(total))),
        dirname
    ))

print(" " + "\033[1m\033[30m-\033[0m" * len(str(total)))
print(" \033[31m%d" % total)

