#!/Users/alexwlchan/.virtualenvs/junkdrawer/bin/python
# -*- encoding: utf-8

import sys

import PyPDF2


if __name__ == "__main__":
    try:
        path = sys.argv[1]
    except IndexError:
        sys.exit(f"Usage: {__file__} <PATH>")

    with open(path, "rb") as stream:
        reader = PyPDF2.PdfFileReader(stream)
        print(reader.getNumPages())
