#!/usr/bin/env python3
# -*- encoding: utf-8
"""
Open a PDF file, then resave it.  macOS only.

This is useful for embedding fonts in PDFs, which aren't supplied by all systems.

e.g. when you download PDFs from Workday at Wellcome, they don't embed their fonts.
This can cause issues with thumbnails in docstore, see
https://github.com/alexwlchan/docstore/issues/125
"""

import filecmp
import pathlib
import shutil
import sys
import uuid

from Foundation import NSURL
from Quartz.PDFKit import PDFDocument


def save_original_copy(path):
    orig_stem = path.stem + "__orig"
    suffix = path.suffix

    stem = orig_stem
    while True:
        p = pathlib.Path(stem + suffix)
        if not p.exists():
            shutil.copyfile(path, p)
            break

        if filecmp.cmp(path, p, shallow=False):
            return

        stem = orig_stem + "_" + str(uuid.uuid4())


def embed_fonts(path):
    path = str(path)
    url = NSURL.fileURLWithPath_(path)
    pdf_doc = PDFDocument.alloc().initWithURL_(url)
    pdf_doc.writeToFile_(path)


if __name__ == '__main__':
    pdf_paths = sys.argv[1:]

    for p in pdf_paths:
        path = pathlib.Path(p)

        print(f"Processing {path}...")

        # Start by saving the original copy of the file, so we know it's safe
        save_original_copy(path)

        # Now embed the fonts!
        embed_fonts(path)
