#!/usr/bin/env python

import datetime
import os


def get_downloads():
    downloads_dir = os.path.join(os.environ["HOME"], "Downloads")

    for f in os.listdir(downloads_dir):
        p = os.path.join(downloads_dir, f)

        if not os.path.isfile(p):
            continue

        if f == ".DS_Store":
            continue

        yield p


def downloaded_time(p):
    return os.stat(p).st_mtime


if __name__ == '__main__':
    print(max(get_downloads(), key=lambda p: downloaded_time(p)))
