#!/usr/bin/env python3

# From https://docs.python.org/3/library/secrets.html#recipes-and-best-practices

import secrets

word_count = secrets.choice([4, 5, 6, 7])

with open("/usr/share/dict/words") as f:
    words = [word.strip() for word in f]
    password = "-".join(secrets.choice(words) for i in range(word_count))

print(password)
