#!/usr/bin/env python

import re, sys

src = sys.argv[1]

lines = []
curr_line = ""
indent = 0

for char in src:
    if char == "(":
        curr_line += char
        lines.append(curr_line)
        indent += 1
        curr_line = "  " * indent
        continue
    elif char == ")":
        lines.append(curr_line)
        indent -= 1
        curr_line = "  " * indent + char
        continue
    elif char == ",":
        curr_line += char
        lines.append(curr_line)
        curr_line = "  " * indent
    else:
        curr_line += char

lines.append(curr_line)
print(re.sub(r"\(\s+\)", "()", "\n".join(lines)))