#!/usr/bin/env bash

set -o errexit
set -o nounset

QUEUE_NAME="$1"

AWS_PROFILE=platform-dev python3 ~/repos/dockerfiles/sqs_redrive/redrive.py \
    --src="https://sqs.eu-west-1.amazonaws.com/760097843905/$QUEUE_NAME" \
    --dst="https://sqs.eu-west-1.amazonaws.com/760097843905/$(echo "$QUEUE_NAME" | sed 's/_dlq//g')"
